# Generated by Django 4.1.5 on 2023-05-08 17:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(default='')),
                ('staff', models.CharField(choices=[('tanks', 'танки'), ('healers', 'лекари'), ('damagedealers', 'ДД'), ('traders', 'торговцы'), ('gildmasters', 'гилды'), ('questgivers', 'квестгиверы'), ('smiths', 'кузнецы'), ('skinners', 'кожевенники'), ('potioners', 'зельевары'), ('spellcasters', 'заклинатели')], default='tanks', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
