# Generated by Django 4.1.5 on 2023-05-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewbody', models.CharField(default='void of emptyness', max_length=255)),
                ('reviewpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no1.post')),
            ],
        ),
    ]
