# Generated by Django 4.1.5 on 2023-05-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no1', '0006_alter_review_acceptance_alter_review_reviewuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='staff',
            field=models.CharField(choices=[('tanks', 'танки'), ('healers', 'лекари'), ('damagedealers', 'ДД'), ('traders', 'торговцы'), ('gildmasters', 'гилды'), ('questgivers', 'квестгиверы'), ('smiths', 'кузнецы'), ('skinners', 'кожевенники'), ('potioners', 'зельевары'), ('spellcasters', 'заклинатели')], default='tanks', max_length=30, verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewbody',
            field=models.CharField(default='void of emptiness', max_length=255, verbose_name='содержание поста'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no1.post', verbose_name='отклик на пост'),
        ),
    ]
