# Generated by Django 4.1.5 on 2023-05-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('no1', '0009_alter_newslist_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
